name: Activity Box

on:
  schedule:
    - cron: '30  1,4,7,10,13,16,19,22 * * *'
    - cron: '0 0,3,6,9,12,15,18,21  * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: node ./index.js
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_USERNAME: NightYoshi370
        GIST_ID: 9430c9b83c3b5482295115982c843520
